import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'


import Dialog from '@/components/ui/Dialog'
import Navbar from '@/components/ui/Navbar'
import Footer from '@/components/ui/Footer'
import { Providers } from './providers'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['500', '700', '800', '900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={poppins.className} suppressHydrationWarning>
        <Providers>

          <Navbar />

          {children}

          <Footer />

          <Dialog />

        </Providers>
      </body>
    </html>
  )
}